#!/usr/bin/env bash
set -euo pipefail

# Guarded F1 VLM runner. It intentionally refuses to start until the
# validation-selected teacher and the complete immutable train cache exist.
readonly REMOTE_HOST="${REMOTE_HOST:-vla101}"
readonly GPU="${CUDA_VISIBLE_DEVICES:-0}"
readonly STEPS="${F1_STEPS:-10000}"
readonly SEEDS="${F1_SEEDS:-17,29,41}"
readonly MODE="${F1_SEMANTIC_LOSS_MODE:-kl}"
readonly LAMBDA="${F1_LAMBDA_SEM:-0.10}"
readonly TEMP="${F1_TEACHER_TEMPERATURE:-1.25}"
echo "Using remote CUDA_VISIBLE_DEVICES=$GPU, steps=$STEPS, seeds=$SEEDS, mode=$MODE"

ssh "$REMOTE_HOST" "CUDA_VISIBLE_DEVICES='$GPU' F1_STEPS='$STEPS' F1_SEEDS='$SEEDS' F1_SEMANTIC_LOSS_MODE='$MODE' F1_LAMBDA_SEM='$LAMBDA' F1_TEACHER_TEMPERATURE='$TEMP' bash -s" <<'REMOTE'
set -euo pipefail
P=/vepfs-mlp2/c20250405/400040/transfer/vla_attention
R="$P/repo/VLA_attention"; PY="$P/envs/p1/bin/python"
MODEL="$P/models/Qwen2.5-VL-7B-Instruct"; DINO="$P/models/DINOv2-ViT-L-14"
DATA="$P/data/flickr30k_entities"
MANIFEST="$R/experiment_workspace/manifests/flickr30k_entities/caption_sft_train_10k_seed17_aligned_phrase.jsonl"
CACHE="$P/teacher_maps/F1_train_sd1_5_nulltext_phrase_10k_seed17"
FROZEN="$R/configs/experiments/P4_vlm_v0_v4_frozen.json"
LORA="$R/configs/qwen_lora_v1.json"
OUT="$P/results/F1_vlm_v0_v4"; CK="$P/checkpoints/F1_vlm_v0_v4"
export PYTHONPATH="$R/src:$R"; cd "$R"

for path in "$PY" "$MODEL" "$DINO" "$DATA" "$MANIFEST" "$CACHE" "$FROZEN" "$LORA"; do
  test -e "$path" || { echo "MISSING_REMOTE=$path" >&2; exit 2; }
done
test "$(python - <<PY
import json
print(len(json.load(open('$FROZEN'))['train_manifest_sha256']))
PY
)" -gt 0
expected=$(wc -l < "$MANIFEST")
actual=$(find "$CACHE" -maxdepth 1 -type f -name '*.npy' | wc -l)
test "$expected" -gt 0 || { echo "EMPTY_TRAIN_MANIFEST" >&2; exit 3; }
test "$actual" -eq "$expected" || { echo "INCOMPLETE_TRAIN_CACHE=$actual/$expected" >&2; exit 3; }
test -f "$CACHE/failures.json"
test "$(python - <<PY
import json
print(len(json.load(open('$CACHE/failures.json'))))
PY
)" -eq 0 || { echo CACHE_FAILURES >&2; exit 3; }

IFS=',' read -r -a seeds <<< "$F1_SEEDS"
mkdir -p "$P/jobs" "$OUT" "$CK"
run_group() {
  local group="$1" seed="$2"; shift 2
  local tag="${group}_seed${seed}_s${F1_STEPS}"
  local out="$OUT/$tag.json" ck="$CK/$tag"
  test ! -e "$out" && test ! -e "$ck" || { echo "ARTIFACT_EXISTS=$tag" >&2; exit 4; }
  echo "START_GROUP=$tag" | tee "$P/jobs/F1_${tag}.log"
  "$PY" "$@" --output "$out" --checkpoint "$ck" --max-steps "$F1_STEPS" --seed "$seed" 2>&1 | tee -a "$P/jobs/F1_${tag}.log"
  test -s "$ck/adapter_model.safetensors"
  test -s "$out"
  echo "DONE_GROUP=$tag" | tee -a "$P/jobs/F1_${tag}.log"
}

# V0 is checkpoint-only; its held-out report is generated by the separate
# official evaluation step after all paired adapters are available.
for seed in "${seeds[@]}"; do
  run_group V1 "$seed" scripts/run_qwen_caption_smoke.py --model "$MODEL" --dataset-root "$DATA" --manifest "$MANIFEST" --lora-config "$LORA"
  run_group V2 "$seed" scripts/run_qwen_v2_smoke.py --model "$MODEL" --dino "$DINO" --dataset-root "$DATA" --manifest "$MANIFEST" --lora-config "$LORA" --lambda-ret 0.10
  run_group V3 "$seed" scripts/run_qwen_v3_smoke.py --model "$MODEL" --dataset-root "$DATA" --manifest "$MANIFEST" --cache "$CACHE" --lora-config "$LORA" --lambda-sem "$F1_LAMBDA_SEM" --teacher-temperature "$F1_TEACHER_TEMPERATURE" --semantic-loss-mode "$F1_SEMANTIC_LOSS_MODE" --common-resolution 16
  run_group V4 "$seed" scripts/run_qwen_v4_smoke.py --model "$MODEL" --dino "$DINO" --dataset-root "$DATA" --manifest "$MANIFEST" --cache "$CACHE" --lora-config "$LORA" --lambda-ret 0.10 --lambda-sem "$F1_LAMBDA_SEM" --teacher-temperature "$F1_TEACHER_TEMPERATURE" --semantic-loss-mode "$F1_SEMANTIC_LOSS_MODE" --common-resolution 16
done
echo F1_VLM_V0_V4_TRAIN_OK
REMOTE
